name: network
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #dio: ^3.0.10
  #dio: ^4.0.0-prev3

  dio: ^4.0.0
  package_info: ^2.0.0
  dio_http2_adapter: ^2.0.0
  data_connection_checker: ^0.3.4
  retrofit: any
  logger: any
  json_annotation: ^4.3.0

  connectivity: ^3.0.2
  core:
    path: ../core


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any



dependency_overrides:
  http: ^0.13.0
  http_parser: ^4.0.0
  share: ^0.6.5+4
  rxdart: ^0.27.1
  permission_handler: ^7.2.0
  logging: ^1.0.0
  source_gen: ^0.8.2
  google_fonts: ^2.0.0
  crypto: ^3.0.0
  json_serializable: any
  analyzer: any
  dio: ^4.0.0
  pubspec_parse: ^1.0.0
  json_annotation: ^4.1.0
  yaml: ^3.0.0


flutter:

